cache:
  yarn: true
  directories:
    - $HOME/.m2
jobs:
  include:
    - stage: test
      language: node_js
      node_js:
        - "10"
      before_install:
        - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
        - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
        - sudo apt-get update -qq
        - sudo apt-get install -y -qq yarn
      before_script:
        - cd workflix/frontend
        - yarn install
      script:
        - yarn lint
        - yarn flow
        - yarn test
    - stage: test
      language: java
      before_script:
        - cd workflix/backend/backend
      script:
        - mvn test
    - stage: build
      language: java
      before_script:
        - cd workflix/backend/backend
      script:
        - mvn -DskipTests=true package
